### ISSUE TITLE
taobao sec-kill还有用吗

### ISSUE THREAD

**Issue by lhhsh4461** [A-dying-ape/demo#1]

**Comment by better319** [comment]
||zzzzddd||cccccc

账号是这个格式吗?
怎么会出现cookies问题呢？




Exception in thread Thread-7:
Traceback (most recent call last):
  File "d:\Program Files\WPy64-3771\python-3.7.7.amd64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "d:\Program Files\WPy64-3771\python-3.7.7.amd64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "d:\Desktop\demo-master\淘宝秒杀4.0\get_cookies.py", line 244, in main
    tb = TB_Login(account, password, chrome_version, updata_log, proxy)
  File "d:\Desktop\demo-master\淘宝秒杀4.0\get_cookies.py", line 34, in __init__
    self.password2 = self._encrypt_password()
  File "d:\Desktop\demo-master\淘宝秒杀4.0\get_cookies.py", line 43, in _encrypt_password
    with open("./password2.js", mode="r", encoding='UTF-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './password2.js'

**Comment by A-dying-ape** [comment]
那可能就是用不了了，这都多久了，淘宝跟新多少版了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月29日(周四) 晚上8:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [A-dying-ape/demo] taobao sec-kill还有用吗 (#1)




 
||zzzzddd||cccccc
 
账号是这个格式吗?
 怎么会出现cookies问题呢？
 
Exception in thread Thread-7:
 Traceback (most recent call last):
 File "d:\Program Files\WPy64-3771\python-3.7.7.amd64\lib\threading.py", line 926, in _bootstrap_inner
 self.run()
 File "d:\Program Files\WPy64-3771\python-3.7.7.amd64\lib\threading.py", line 870, in run
 self._target(*self._args, **self._kwargs)
 File "d:\Desktop\demo-master\淘宝秒杀4.0\get_cookies.py", line 244, in main
 tb = TB_Login(account, password, chrome_version, updata_log, proxy)
 File "d:\Desktop\demo-master\淘宝秒杀4.0\get_cookies.py", line 34, in init
 self.password2 = self._encrypt_password()
 File "d:\Desktop\demo-master\淘宝秒杀4.0\get_cookies.py", line 43, in _encrypt_password
 with open("./password2.js", mode="r", encoding='UTF-8') as f:
 FileNotFoundError: [Errno 2] No such file or directory: './password2.js'

**Comment by better319** [comment]
好吧，期待你的佳作！

**Comment by lhhsh4461** [comment]
淘宝那个可以更新一下吗

**Comment by listen120** [comment]
谁有淘宝秒杀仙女版之类的，可以做到0秒付的   加我V:_Lin_Dao  冒号之后的名字哈，重金酬谢
